[package]
name = "depotd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "The depot daemon"

[dependencies]
depot-core = { path = "../depot-core" }
serde_json = "1"
ureq = { version = "3", default-features = false, features = ["rustls"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
] }
