[package]
name = "depotd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "The depot daemon"

[dependencies]
fs2 = "0.4"
depot-core = { version = "0.1.0", path = "../depot-core" }
rusqlite = { version = "0.40.2", default-features = false, features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "1.1.6"
ureq = { version = "3", default-features = false, features = ["rustls"] }

[dev-dependencies]
tempfile = "3.27.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
] }
